config/routes.rb
Rails.application.routes.draw do
	get "/locations_list", to: "home#locations_list"

  	resources :offices do
		resources :locations
	end

  	root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :office
	attr_accessor :distance
  	acts_as_mappable :default_units => :miles, #As You Can see here my default unit is in miles
                   :default_formula => :sphere, #:sphere Haversine calculations instead of :flat which gives gives the Pythagoreum Theory
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude
	
	validates_presence_of :address_line_1, :city, :postcode
	validates_uniqueness_of :postcode
	validate :validate_postcode

	def full_address
		[address_line_1, town, city, postcode].compact.join(", ")
	end

	def validate_postcode # 
		lookup = PIO.lookup(postcode.to_s)
		if lookup.try(:info).blank?
			errors.add(:postcode, "doesn't exist!")
		else
			self.longitude = lookup.longitude
			self.latitude = lookup.latitude
		end
	end


  def self.offices_within(latitude, longitude, radius) #The main heart of everything. We can also search in range of radius not less that 1 and not more than 2 miles like Location.within([1..2], origin)
    return self.within(radius, :origin => [latitude, longitude]).all
    .each{|a| a.distance = a.distance_from([latitude, longitude])} #I addedd attr_accessor distance (This is the distance_from the given postcode to the office location) I need to use the distance to sort and as well in the view
    .sort {|a,b| a.distance <=> b.distance }  
  end

end

app/models/office.rb
class Office < ApplicationRecord
	has_many :locations, dependent: :destroy
	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@postcode = nil
	end

	def locations_list
		@postcode = params[:query_data][:postcode]
		if !@postcode.blank?
			lookup = PIO.lookup(@postcode)
		elsif !params[:query_data][:latitude].blank? && !params[:query_data][:longitude].blank?
			postcodes = PIO.reverse_geocode(longitude: params[:query_data][:longitude].to_f, latitude: params[:query_data][:latitude].to_f)
			@postcode = postcodes.last.postcode
			lookup = PIO.lookup(@postcode)
		else
			lookup = {}	
		end
		
		if !lookup.try(:info).blank?
			start = params[:start].blank? ? 0 : params[:start].to_i
			length = params[:length].blank? ? 10 : params[:length].to_i
			@total_locations = Location.offices_within(lookup.latitude, lookup.longitude, params[:query_data][:radius])
	    @locations = @total_locations[start, length]
	    data = Array.new
 			@locations.each do |loc|
	      tmpdata = Array.new
	      #tmpdata.push(loc.id)
	      tmpdata.push(loc.office.name.to_s.titleize)
	      tmpdata.push(loc.full_address)
	      tmpdata.push(loc.distance.round(1))
	      data.push(tmpdata)
      end	      
      	render json: {draw: params[:draw], recordsTotal: @total_locations.count, recordsFiltered: @total_locations.count, data: data, postcode: @postcode}    		
		else
			render json: {draw: params[:draw], recordsTotal: 0, recordsFiltered: 0, data: []}
		end    	
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_office
  # GET /locations
  # GET /locations.json
  def index    
    @locations = @office.locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @location.office = @office
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.js
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to office_location_path(@office, @location), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to office_locations_url(@office), notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location      
      @location = Location.find(params[:id])
    end

    def set_office
      @office = Office.find_by_id(params[:office_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.fetch(:location, {}).permit!
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.js
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.js
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.fetch(:office, {}).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/home/_search_form.html.erb
<div class="seach-box">
		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
					<%= hidden_field_tag "latitude" %>
					<%= hidden_field_tag "longitude" %>
					<label> Postcode </label>
					<%= text_field_tag "postcode", @postcode, class: "form-control", style: "text-align: center;"%>
				</div>
				<div class="form-group">
					<label> Radius </label>					
					<div class="text-center">
						<span id="distance"></span> miles <br/>
						<%= text_field_tag "radius", nil, data:{"slider-id"=>"radiusSlider", "slider-value" => "5", "slider-min" => "0.1", "slider-max"=>"50"}, class: "form-control"%>
					</div>
				</div>
			</div>
		</div>
</div>

app/views/home/index.html.erb
 <%= render partial: 'search_form' %>
<br/>
<div class="box-body">
  <table id="locations_list" class="table table-bordered table-striped display responsive nowrap" width="100%" cellspacing="0">
    <thead>
    <tr>
      <th>Office</th>
      <th>Address</th>
       <th>Distance (miles)</th>      
    </tr>
    </thead>
    <tbody>

    </tbody>

  </table>
</div>

<% content_for :page_level_script do %>
    <script type="text/javascript">
    	 // location_list_table.draw();
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delivery Office Locator</title>    
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    
    <%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track': 'reload' %>  
   
  </head>

  <body>
  	<%= render 'shared/nav_bar'%>
  	<div class="container">
    	<%= yield %>
		</div>
    
    <div id="dynamic-modal"  class="modal fade">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
    <!--       <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div> -->
          <div id="modal-content" class="modal-body"  style="overflow:hidden;">

          </div>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>      		
  </body>
</html>

app/views/locations/_form.html.erb
<h2><%= location.new_record? ? "New" : "Update" %> Office</h2>
  <div class="add-crud-edit-errors error-wrapper"></div>
  <div id = "error-edit-inner-div" >
  </div>
  <% action = location.persisted? ?  'update': 'create'%>
<%= form_for location, url: {action: action}, authenticity_token: true,remote:true, html: {style: "padding: 10px;"} do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <label><%= form.label :address_line_1%></label>
      <%= form.text_field :address_line_1, class: "form-control" %>
    </div>
    <div class="form-group">
      <label><%= form.label :address_line_2%></label>
      <%= form.text_field :address_line_2, class: "form-control" %>
    </div>
    <div class="form-group">
      <label><%= form.label :city%></label>
      <%= form.text_field :city, class: "form-control" %>
    </div>     
    <div class="form-group">
      <label><%= form.label :town%></label>
      <%= form.text_field :town, class: "form-control" %>
    </div> 
    <div class="form-group">
      <label><%= form.label :postcode%></label>
      <%= form.text_field :postcode, class: "form-control" %>
    </div>                     
  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger close-modal" data-dismiss="modal">Cancel</button>
  </div>
<% end %>

app/views/locations/_table_row.html.erb
  <tr>
    <td><%= location.id %></td>
    <td><%= location.full_address %></td>
    <td><%= link_to 'Edit', edit_office_location_path(@office, location) %></td>
    <td><%= link_to 'Destroy', office_location_path(@office, location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/locations/create.js.erb
<% if @location.errors.any?%>
	<%= render partial: "shared/error", locals: {obj: @location} %>
<% else %>
	<%= render partial: "shared/success", locals: {obj: "Office created successfully"} %>
	$('#tr-append').append("<%= escape_javascript(render partial: 'table_row', locals: {office: @office, location: @location} ) %>")
<% end %>

// hideLoader();

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location, office: @office %>

<%= link_to 'Show', office_location_path(@office, @location) %> |
<%= link_to 'Back', office_locations_path(@office) %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @office.name.to_s.titleize%> Office Locations </h1>
<a href="#" data-id="" data-url="<%= new_office_location_path(@office, format: :js) %>" class="btn btn-success dynamic-modal-trigger" data-toggle="modal" data-target="#dynamic-modal"><b> Add Location </b></a>
<br/>
<br/>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Address</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody id="tr-append">
    <% @locations.each do |location| %>
      <%= render partial: 'table_row', locals: {location: location, office: @office} %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Office Lists', offices_path(@office) %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%#= link_to 'Back', locations_path %>

app/views/locations/new.js.erb
$('#modal-content').html("<%= escape_javascript render 'form', office: @office, location: @location %>")
$( "form" ).submit(function( ) {
    $('.add-crud-edit-errors').html(pleaseWait());
});
ajaxSubmit();

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_office_location_path(@office, @location) %> |
<%= link_to 'Back', office_locations_path(@office) %>

app/views/offices/_form.html.erb
<h2><%= office.new_record? ? "New" : "Update" %> Office</h2>
  <div class="add-crud-edit-errors error-wrapper"></div>
  <div id = "error-edit-inner-div" >
  </div>
  <% action = office.persisted? ?  'update': 'create'%>
<%= form_for office, url: {action: action}, authenticity_token: true,remote:true, html: {style: "padding: 10px;"} do |form| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <label><%= form.label :name%></label>
      <%= form.text_field :name, class: "form-control" %>
    </div>  
  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
    <button type="button" class="btn btn-danger close-modal" data-dismiss="modal">Cancel</button>
  </div>
<% end %>

app/views/offices/_table_row.html.erb
  <tr>
    <td><%= office.id %></td>
    <td><%= office.name %></td>
    <td><%= link_to "Locations (#{office.locations.count})", office_locations_path(office) %></td>
    <td><%= link_to 'Edit', edit_office_path(office) %></td>
    <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/offices/create.js.erb
<% if @office.errors.any?%>
	<%= render partial: "shared/error", locals: {obj: @office} %>
<% else %>
	<%= render partial: "shared/success", locals: {obj: "Office created successfully"} %>
	$('#tr-append').append("<%= escape_javascript(render partial: 'table_row', locals: {office: @office} ) %>")
<% end %>

// hideLoader();

app/views/offices/edit.html.erb
<h1>Editing Office</h1>

<%= render 'form', office: @office %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offices</h1>
<%#= link_to 'New Office', new_office_path %>
<a href="#" data-id="" data-url="<%= new_office_path(format: :js) %>" class="btn btn-success dynamic-modal-trigger" data-toggle="modal" data-target="#dynamic-modal"><b> New Office </b></a>
<br/>
<br/>
<% if  !@offices.blank? %>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody id="tr-append">
      <% @offices.each do |office| %>
        <%= render partial: 'table_row', locals: {office: office} %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    <em>No office(s) found.</em>
  </p>
<% end %>
<br>

app/views/offices/new.html.erb
<%= render 'form', office: @office %>

<%= link_to 'Back', offices_path %>

app/views/offices/new.js.erb
$('#modal-content').html("<%= escape_javascript render 'form', office: @office %>")
$( "form" ).submit(function( ) {
    $('.add-crud-edit-errors').html(pleaseWait());
});
ajaxSubmit();

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>

app/views/shared/_error.js.erb
$(".add-crud-edit-errors").empty();
$('<div>', {
    id: 'error_explanation_edit'
}).append($('<div>', {
    id: 'error-edit-inner-div',
    class: "alert alert-danger"
})).appendTo('.add-crud-edit-errors');
var list = $("#error-edit-inner-div").append('<ul></ul>').find('ul');
<% obj.errors.full_messages.each do |msg| %>
list.append("<li><%= msg %></li>");
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-dark bg-dark fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">DO Locator v1.0.0</a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/offices">Office & Locations</a>
      </li>
<!--       <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
<!--     <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/shared/_success.js.erb
$(".add-crud-edit-errors").empty();
$('<div>', {
    id: 'error_explanation_edit'
}).append($('<div>', {
    id: 'error-edit-inner-div',
    class: "alert alert-success"
})).appendTo('.add-crud-edit-errors');
var list = $("#error-edit-inner-div").append('<ul></ul>').find('ul');
list.append("<li><%= obj %></li>");

setTimeout(function () {
    $('#error-edit-inner-div').fadeOut(300, function(){ $(this).empty();});
    //$(".error-edit-inner-div").empty()
}, 1500);
setTimeout(function () {
    $(".close-modal").click();
    $('#modal-content').html("")
}, 1000);